### PR TITLE
Feature/custom error icon

### PR DESCRIPTION
**Pull request by moosefaceee**
This PR implements the functionality mentioned in https://github.com/jeanverster/chakra-ui-steps/issues/90

### CODE REVIEW

**Comment by moosefaceee** [comment]
Apologies I see one linting difference we have in wrapping

**Comment by moosefaceee** [comment]
Strange I have pulled in the latest develop, checking and resolving cornflakes

**Comment by moosefaceee** [comment]
👀

**Review by jeanverster — APPROVED** [review]
Hey @moosefaceee - apologies for not reviewing this sooner, lots on the go recently so haven't had a chance to tend to this repo.. PR looks good! Will ping you once I've released these changes

**Pull request merged**
