### PR TITLE
feat(hooks): add goto hook

### PR DESCRIPTION
**Pull request by mattf96s**
Hey Jean

I was wondering if you would be willing to add a way to programmatically move between steps. Would help with syncing against url state (with react-router). 

Really enjoying the library 👍 
Thanks

### CODE REVIEW

**Comment by jeanverster** [comment]
Sup Matt! Thanks for submitting this. Think it would be a good thing to add. Just a few things:

1. I think we should maybe call it `setStep` to keep the naming convention inline with `prevStep` and `nextStep` etc.. 
2. I just noticed that the hook isn't defined in the readme, might be worth adding?
3.  Target branch needs to be changed to `develop` and not `main`

Otherwise looks good

**Comment by mattf96s** [comment]
Cool thanks Jean. 

Will make the changes later this evening 👍

**Review by jeanverster — APPROVED** [review]
Looks good Matty 👍🏼 Sorry about the late approval. Will merge and do a new release

**Comment by jeanverster** [comment]
@mattf96s this has been release in v1.3.0

**Comment by mattf96s** [comment]
Hey Jean, thanks so much (sorry, have been away) 👍

**Pull request merged**
