### PR TITLE
Make it possible to defined checkIcon and state at each Step

### PR DESCRIPTION
**Pull request by mellson**
Thanks for creating this lovely library; it's excellent! I started using it today and need a way to set the `checkIcon` and `state` at each step. I'm using it for a consent dialog and want to show the error state for a single step if a consent is declined. And maybe even using a different icon. Let me know what you think.

### CODE REVIEW

**Comment by jeanverster** [comment]
Hey @mellson - thanks for this, and sorry I'm only responding now.. PR looks good, I've recently made some updates so there's currently some conflicts which need resolving.. Also a aouple things, could you please change the base branch to `develop`, and it would be nice to add a storybook example of how this might work? You can run storybook using `yarn storybook` in the `chakra-ui-steps` directory.

**Comment by mellson** [comment]
> Hey @mellson - thanks for this, and sorry I'm only responding now.. PR looks good, I've recently made some updates so there's currently some conflicts which need resolving.. Also a aouple things, could you please change the base branch to `develop`, and it would be nice to add a storybook example of how this might work? You can run storybook using `yarn storybook` in the `chakra-ui-steps` directory.

Thank you for the feedback. I've tried to add a few Storybook examples. And another prop `isKeepError` that will allow keeping the errors red if it's in an error state.

**Comment by mellson** [comment]
Hi @jeanverster 👋 sorry for the bump, but did you get a chance to look at the updates?

**Comment by jeanverster** [comment]
Hey @mellson - apologies for the delay here, work has been real busy the last few weeks. I just had a look at the updates and they look good! Will merge this and try get it released this weekend sometime 👌 Thanks for this!

**Comment by mellson** [comment]
> Hey @mellson - apologies for the delay here, work has been real busy the last few weeks. I just had a look at the updates and they look good! Will merge this and try get it released this weekend sometime 👌 Thanks for this!

Awesome, thank you! I look forward to trying out the upcoming release. Thanks again for creating this 🙇🏻

**Pull request merged**
